In [14]:
import os
import plotly.express as px
import hvplot.pandas
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

True

In [15]:
property_df = pd.read_csv("../Data/PropertyTraits.csv")
property_df.head()

,Unnamed: 0,PropertyID,Type,State,Price,Features,Bathrooms,Bedrooms,Carspaces,Area,Suburb,Postcode,Latitude,Longitude
0,0,2016723553,Sale,QLD,349000,"['SwimmingPool', 'Furnished', 'Gym']",1.0,1.0,1,City & North,BRISBANE CITY,4000,-27.46224,153.0309
1,1,2016727278,Sale,QLD,140000,"['CableOrSatellite', 'SwimmingPool', 'Furnishe...",1.0,na,na,City & North,BRISBANE CITY,4000,-27.4732361,153.02713
2,2,2016806859,Sale,QLD,559000,"['AirConditioning', 'BuiltInWardrobes', 'Cable...",2.0,2.0,1,City & North,BRISBANE CITY,4000,-27.4705048,153.029892
3,3,2016834181,Sale,QLD,329000,"['AirConditioning', 'BuiltInWardrobes', 'Secur...",1.0,1.0,1,City & North,BRISBANE CITY,4000,-27.46224,153.0309
4,4,2016837531,Sale,QLD,384000,"['AirConditioning', 'BuiltInWardrobes', 'Gas',...",1.0,1.0,1,City & North,BRISBANE CITY,4000,-27.472084,153.0285

In [26]:
new_df = property_df[["PropertyID", "Price", "Latitude", "Longitude"]]
new_df.head()

   PropertyID   Price     Latitude   Longitude
0  2016723553  349000    -27.46224    153.0309
1  2016727278  140000  -27.4732361   153.02713
2  2016806859  559000  -27.4705048  153.029892
3  2016834181  329000    -27.46224    153.0309
4  2016837531  384000   -27.472084    153.0285

In [29]:
new_df["Latitude"] = new_df["Latitude"].astype(int)

ValueError: invalid literal for int() with base 10: '-27.46224'

In [16]:
# Read the Mapbox API key
map_box_api = os.getenv("MAPBOX_API_KEY")

# Set the Mapbox API
px.set_mapbox_access_token(map_box_api)

In [18]:
plot1 = px.scatter_mapbox(new_df,
                          lat='Latitude',
                          lon='Longitude',
                          color='PropertyID')

plot1.show()

TypeError: Could not convert -27.46224-27.4732361-27.4705048-27.46224-27.472084-27.4705048-27.46224-27.4623528-27.4719563-27.4626713-27.472681-27.464283-27.4705048-27.465168-27.46295-27.465168-27.47036-27.465168-27.47036-27.4705048-27.4719563-27.4705048-27.4705048-27.4721432-27.4660988-27.4705048-27.472084-27.4717636-27.47036na-27.46262-27.4626026-27.46358-27.315733-27.3012543 to numeric